#pragma once
#ifndef ERR_H
#define ERR_H

enum ERR {
	NO_ERR,
	ERR_PLAINTEXT_TO_BIGNUM,
	ERR_CIPHERTEXT_TO_BIGNUM,
	ERR_NOT_ENOUGH_SIZE_N,
	ERR_TEXT_STRUCTURE,
	ERR_NO_PUBLICKEY,
	ERR_NO_PRIVATEKEY
};

#endif
